POST https://apitest.authorize.net/xml/v1/request.api
Content-Type: application/json

# const merchantCustomerId = ref('71001')
# const customerPaymentProfileId = ref('521425778')
# const customerProfileId = ref('514324677')

{
    "createTransactionRequest": {
        "merchantAuthentication": {
            "name": "8dzC8Xb48hf",
            "transactionKey": "5s59CE9D9Jb4Cmwr"
        },
        "refId": "1",
        "transactionRequest": {
            "transactionType": "authCaptureTransaction",
            "amount": "5",
            "payment": {
                "creditCard": {
                    "cardNumber": "5424000000000015",
                    "expirationDate": "2025-12",
                    "cardCode": "999"
                }
            },
            "lineItems": {
                "lineItem": {
                    "itemId": "1",
                    "name": "vase",
                    "description": "Cannes logo",
                    "quantity": "18",
                    "unitPrice": "45.00"
                }
            },
            "tax": {
                "amount": "4.26",
                "name": "level2 tax name",
                "description": "level2 tax"
            },
            "duty": {
                "amount": "8.55",
                "name": "duty name",
                "description": "duty description"
            },
            "shipping": {
                "amount": "4.26",
                "name": "level2 tax name",
                "description": "level2 tax"
            },
            "poNumber": "456654",
            "customer": {
                "id": "99999456654"
            },
            "billTo": {
                "firstName": "Ellen",
                "lastName": "Johnson",
                "company": "Souveniropolis",
                "address": "14 Main Street",
                "city": "Pecan Springs",
                "state": "TX",
                "zip": "44628",
                "country": "US"
            },
            "shipTo": {
                "firstName": "China",
                "lastName": "Bayles",
                "company": "Thyme for Tea",
                "address": "12 Main Street",
                "city": "Pecan Springs",
                "state": "TX",
                "zip": "44628",
                "country": "US"
            },
            "customerIP": "192.168.1.1",
            "transactionSettings": {
                "setting": {
                    "settingName": "testRequest",
                    "settingValue": "false"
                }
            },
            "userFields": {
                "userField": [
                    {
                        "name": "MerchantDefinedFieldName1",
                        "value": "MerchantDefinedFieldValue1"
                    },
                    {
                        "name": "favorite_color",
                        "value": "blue"
                    }
                ]
            },
            "processingOptions": {
              "isSubsequentAuth": "true"
            },
            "subsequentAuthInformation": {
             "originalNetworkTransId": "123456789NNNH",
             "originalAuthAmount": "45.00",
             "reason": "resubmission"
            },
            "authorizationIndicatorType": {
            "authorizationIndicator": "final"
          }
        }
    }
}
