POST https://apitest.authorize.net/xml/v1/request.api
Content-Type: application/json

{
    "createCustomerProfileRequest": {
        "merchantAuthentication": {
            "name": "8dzC8Xb48hf",
            "transactionKey": "5s59CE9D9Jb4Cmwr"
        },
        "profile": {
            "merchantCustomerId": "Merchant_Customer_ID",
            "description": "Profile description here",
            "email": "customer-profile-email@here.com",
            "paymentProfiles": {
                "customerType": "individual",
                "payment": {
                    "creditCard": {
                        "cardNumber": "4111111111111111",
                        "expirationDate": "2025-12"
                    }
                }
            }
        },
        "validationMode": "testMode"
    }
}
