version: "3.8"

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.31
    container_name: turborepo_mysql
    restart: always
    environment:
      MYSQL_DATABASE: turborepo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      SA_PASSWORD: 'Pr1sm4_Pr1sm4'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - db:/var/lib/mssql
volumes:
  db:
    driver: local
